# Generated by Django 6.0 on 2025-12-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesListApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='watchlist',
            field=models.URLField(blank=True, null=True),
        ),
    ]
