# Generated by Django 6.0 on 2025-12-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesListApp', '0002_movies_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='poster',
            field=models.URLField(blank=True, null=True),
        ),
    ]
